name: releaser

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  releaser:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract script name
      run: |
        REPO_BASE=$(basename "${{ github.repository }}")
        MIDDLE_PART=$(echo "$REPO_BASE" | sed 's/AviUtl2_\(.*\)_Script/\1/')
        echo "SCRIPT_NAME=$MIDDLE_PART" >> $GITHUB_ENV

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Build script
      run: |
          pip install git+https://github.com/korarei/AviUtl2_Astra.git@v0.3.0
          cd ${{ github.workspace }}/scripts
          astra build -v ${{ github.ref_name }}
          astra release

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ env.SCRIPT_NAME }}_${{ github.ref_name }}
        files: 'scripts/release/*.zip'
        body_path: scripts/release/release_notes.txt
